name: API Tests with Newman

on:
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run "E-Commerce API QA Automation.postman_collection.json" \
          -e "E-Commerce QA Environment.postman_environment.json"